# KarmaPlugin configuration

thresholds:
  good: 50
  evil: -50

values:
  # Legacy default for all player kills (used as fallback for the specific keys below)
  kill_player: -20
  # Specific deltas by victim alignment (override legacy kill_player):
  # Killing an EVIL player should raise karma (defaults to +10)
  kill_player_evil: 10
  # Killing a GOOD player should lower karma (defaults to -20)
  kill_player_good: -20
  # Killing a NEUTRAL player (defaults to -5)
  kill_player_neutral: -5
  kill_villager: -15
  kill_evil_mob: 10
  max_abs_karma: 9999
  evil_max_health: 14.0

# Interval in seconds for periodic effects and display updates
interval_seconds: 5

display:
  bossbar_enabled: true
  name_tag_enabled: true
  name_color_enabled: true
  particles_enabled: true
  chat_enabled: false
  bossbar_style: SEGMENTED_12
  bossbar_titles:
    good: "Karma: %value% (Good)"
    neutral: "Karma: %value% (Neutral)"
    evil: "Karma: %value% (Evil)"
  name_tag:
    good_prefix: "&a[Good] "
    neutral_prefix: "&7[Neutral] "
    evil_prefix: "&c[Evil] "

evil_mobs: [ZOMBIE, HUSK, DROWNED, SKELETON, STRAY, WITHER_SKELETON, CREEPER, SPIDER, CAVE_SPIDER, ENDERMAN, PHANTOM, WITCH, PILLAGER, VINDICATOR, RAVAGER, SLIME, MAGMA_CUBE]

colors:
  good: "&a"
  neutral: "&7"
  evil: "&c"


