name: KarmaPlugin
main: com.gir0fa.karmaPlugin.KarmaPlugin
version: ${project.version}
api-version: '1.21'
authors: [Gir0fa]
description: ${project.description}
commands:
  karma:
    description: View and manage karma
    usage: /karma [get|give|take|set|reload] ...
    aliases: [k]
    permission: karma.use
permissions:
  karma.use:
    default: true
  karma.view.others:
    default: op
  karma.admin:
    default: op
