name: Build and Draft Release

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Release title (optional)'
        required: false

jobs:
  build:
    name: Build Plugin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Build with Maven
        run: mvn -B -q clean package

      - name: Extract Maven version
        id: get_version
        run: |
          VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:3.1.0:exec)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create draft release and upload JAR(s)
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          tag_name: v${{ steps.get_version.outputs.version }}
          name: ${{ github.event.inputs.title || format('Release v{0}', steps.get_version.outputs.version) }}
          files: |
            target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}


